name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1 # Replace with your region

      - name: Set up SSH key
        run: |
          echo "${{ secrets.PEM_FILE }}" > key.pem
          chmod 600 key.pem

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@ec2-3-110-1-202.ap-south-1.compute.amazonaws.com 'bash deploy_script.sh'
