name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_PEM_FILE }}

      - name: Run deploy script on EC2
        run: ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-110-1-202.ap-south-1.compute.amazonaws.com 'bash deploy_script.sh'
